%% Tutorial Script 3:permutationControl_computeHERs
%
% This script recomputes HER trialDefs based on semi-random "permuted R peaks".
% The permuted R's are generated by taking the differences between stim onsets and
% their true corresponding HER R peaks (which is already computed and saved in
% the true trialDef_Rpeaks, col 5), and shuffling that vector. For each
% trial, a new "permuted R" is then determined as stim onset minus one of
% the permuted stim-to-R differences. A new trialDef_Rpeaks_permuted is
% generated around that permuted R using HER_timeWindow.
% The function loops over all subjects and loads their real R_trialDef.
% It produces n_permutations amounts of new random R_trialDefs.
%
% !!! 
% In practice, we only have the data for subject 26 (index 18 in our included_subjects 
% list) so we are commenting out the looping and just running the script for this subject.
% !!!
%
%
% INPUTS: To set in INIT cell
% - paths
% - included_subjects: List of all subjects included in analysis
% - all_blocks = list of block names ran per subject
% - HER_timeWindow: The window of time [-T1 T2] in seconds used to cut out EEG data
%       around R peaks to constitute HER epochs.
% - n_permutations: number of times we want to permute HER data, e.g. 500
% - fs_physio: sampling rate in Hz for EEG data
% The script also loads, for each subject:
% - <filePrefix>_HER_events.mat : contains trialDef_Rpeaks, the structure 
%       defining real HER epochs of interest that was used for the main
%       analysis, ie already only fo clean trials etc. It is organised like
%       a FieldTrip trialDef matrix ready for epoching using ft_definetrials:
%           (:,1) ... HER epoch start sample (T1 s before R peak)
%           (:,2) ... HER epoch end sample (T2 after R peak)
%           (:,3) ... offset in samples so that data's 0 time point is centred on R peak
%           (:,4) ... trialIndices, to identify which trial's HER epoch this is
%           (:,6) ... latency between stimulus onset and R peak in seconds - negative since R peak happens before stim
%           the other columns are not important here
%
% OUTPUTS:
% - <filePrefix>_permutedHER_events.mat, contains:
%       - trialDef_Rpeaks_allPermutations_allBlocks defining n_permutations 
%           permuted HER epochs per block, where for each  the columns are
%           organised like above
%
% AUTHOR:
% Marie Loescher - July 2025


%% INIT

clear all
paths = TUTORIAL_setPaths();

load([paths.main 'Data' filesep 'included_subjects.mat'],'included_subjects')
all_blocks = ["01","02","03","04","05"];

fs_physio = 1024; % sampling rate in Hz
HER_timeWindow = [-0.03 0.6]; % time window around R peaks for HER epoching, in seconds
n_permutations = 500;


%%

for subject = 18 %1:length(included_subjects) % we skip the loop and only run on our example subject
    subject_nr = convertStringsToChars(included_subjects(subject));

    load([paths.main 'Data' filesep 'sub-' subject_nr filesep 'sub-' subject_nr '_HER_events.mat'], 'trialDef_Rpeaks_allBlocks');

    for block = 1:length(all_blocks)
        block_nr = convertStringsToChars(all_blocks(block));

        trialDef_Rpeaks = trialDef_Rpeaks_allBlocks{1,block}; % select this block's epoch definitions

        for permutation = 1:n_permutations
    
            % Permute R timings
            stimToR = trialDef_Rpeaks(:,6).*fs_physio; % in this example, stimulus-to-Rpeak latency in seconds (negative values because R is before stim onset) is already stored for each HER epoch in the 6th column of trialDef_Rpeaks. We convert timing to samples.
            stim_samples = trialDef_Rpeaks(:,1) - trialDef_Rpeaks(:,3) + -1*(stimToR); % retrieve samples of stimulus onsets using stimToR
            stimToR_permuted = stimToR(randperm(length(stimToR)));
            R_permuted = stim_samples + stimToR_permuted; % keep in mind that stimToR_permuted is negative

            % Recreate new shuffled "HER" epochs in a time window around R peak defined by HER_timewindow
            peakcounter = 1;
            for peak = 1:size(R_permuted,1)
                trialDef_Rpeaks_permuted(peakcounter,1) = R_permuted(peak) + round(HER_timeWindow(1)*fs_physio); % epoch start
                trialDef_Rpeaks_permuted(peakcounter,2) = R_permuted(peak) + round(HER_timeWindow(2)*fs_physio); % epoch end
                trialDef_Rpeaks_permuted(peakcounter,3) = round((HER_timeWindow(1)*fs_physio)); % offset
                trialDef_Rpeaks_permuted(peakcounter,4) = trialDef_Rpeaks(peak,4); % take over trialindex info
                trialDef_Rpeaks_permuted(peakcounter,5) = stimToR_permuted(peak); % new stim-to-R latencies in seconds
                peakcounter = peakcounter + 1;
            end

            % sort structures by trial index
            trialDef_Rpeaks_permuted = sortrows(trialDef_Rpeaks_permuted,4);

            % store shuffled trialDefs in common structure across blocks
            trialDef_Rpeaks_allPermutations_allBlocks{block,permutation} = trialDef_Rpeaks_permuted;
            clear trialDef_Rpeaks_permuted
        end
    end
    
    save([paths.main 'Data' filesep 'sub-' subject_nr filesep 'sub-' subject_nr '_permutedHER_events.mat'], 'trialDef_Rpeaks_allPermutations_allBlocks');
    clear trialDef_Rpeaks_allPermutations_allBlocks
end

    



   